[[redirects]]
  from = "/sc/*"
  to = "https://internal-api.stickers.cloud/v1/with-packs/:splat"
  status = 200
  force = true
  headers = {origin = "https://stickers.cloud"}

[[redirects]]
  from = "/img/*"
  to = "https://img.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/s1/*"
  to = "https://s1.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/s2/*"
  to = "https://s2.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/s3/*"
  to = "https://s3.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/s4/*"
  to = "https://s4.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/s5/*"
  to = "https://s5.stickers.cloud/packs/:splat"
  force = true
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"