[[redirects]]
  from = "/sc"
  to = "https://internal-api.stickers.cloud/v1/pack/"
  status = 200
  force = true

[[redirects]]
  from = "/img"
  to = "https://img.stickers.cloud/packs"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Origin = "https://stickers.cloud"
    Access-Control-Allow-Origin = "*"