[[redirects]]
  from = "/sc/*"
  to = "https://internal-api.stickers.cloud/v1/pack/:splat"
  status = 200
  headers = {origin = "https://stickers.cloud"}

[[redirects]]
  from = "/img/*"
  to = "https://img.stickers.cloud/packs/:splat"
  status = 200


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"