[[redirects]]
  from = "/sc"
  to = "https://internal-api.stickers.cloud/v1/pack/"
  status = 200
  force = true    
  headers = {Origin = "https://stickers.cloud"}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"